// node analysis/verificar_p3.cjs — contratos de estado y conservación, sin dependencias.
const assert = require('node:assert/strict');
const fs = require('node:fs');
assert.ok(fs.existsSync('prototipo-3d/milpa360-modelo.js'), 'Falta el modelo independiente del render');
const { Modelo, comparar } = require('../prototipo-3d/milpa360-modelo.js');
const datos = require('../prototipo-3d/milpa360-datos.js');
const crear = () => new Modelo(datos, {autorizacionesIlustrativas: true});
const a=crear(), b=crear();
a.avanzar(32); for(let i=0;i<256;i++) b.avanzar(0.125);
assert.deepEqual(a.estado,b.estado,'La partición del tiempo cambia el resultado');
const pausa=JSON.stringify(a.estado); a.avanzar(0); assert.equal(JSON.stringify(a.estado),pausa);
assert.throws(()=>a.avanzar(-1)); assert.throws(()=>a.avanzar(Infinity));
const seguro=new Modelo(datos); seguro.avanzar(9);
assert.equal(seguro.estado.pasos,0,'Sin resultados no puede cruzar S8');
const fallo=crear(); fallo.fallar('lote'); fallo.avanzar(9);
assert.equal(fallo.estado.pasos,0); const masa=fallo.masaSustrato();
fallo.aislar(); fallo.avanzar(1); assert.equal(fallo.masaSustrato(),masa);
assert.equal(fallo.estado.cuarentena.length,1); assert.equal(fallo.estado.repuestos.length,1);
const atasco=crear(); atasco.fallar('atasco'); atasco.avanzar(20);
assert.equal(atasco.estado.pasos,0); assert.equal(atasco.estado.sol,20);
atasco.reparar('atasco'); atasco.avanzar(1); assert.ok(atasco.estado.pasos>0);
const seco=crear(); seco.fallar('bomba'); seco.avanzar(20);
assert.ok(seco.estado.lotes.some(l=>l.cultivos.some(c=>c.muerta)),'La sequía extrema debe dejar daño persistente');
const ids=seco.estado.lotes.filter(l=>l.cultivos.some(c=>c.muerta)).map(l=>l.id);
seco.reparar('bomba'); seco.avanzar(0.125);
assert.ok(seco.estado.lotes.filter(l=>ids.includes(l.id)).some(l=>l.cultivos.some(c=>c.muerta)),'Una planta muerta no revive al reparar');
for(const m of [a,b,fallo,atasco,seco]) m.verificar();
a.avanzar(1000); assert.equal(a.estado.sol,datos.geometria.mision.soles_horizonte); a.verificar();
const fin=JSON.stringify(a.estado); a.avanzar(10); assert.equal(JSON.stringify(a.estado),fin,'El horizonte reinicia inventarios');
const x=comparar(datos,{inicio:40,duracion:21,fraccionLuz:0.25,soles:160});
assert.equal(x.escalonada.area,x.sincronizada.area);
assert.ok(Math.abs(x.escalonada.inicialKcal-x.sincronizada.inicialKcal)<1e-8,'Comparación con distinta biomasa inicial');
assert.ok(Math.abs(x.escalonada.kWh-x.sincronizada.kWh)<1e-8,'Comparación con energía distinta');
const sinFallo=comparar(datos,{inicio:40,duracion:0,fraccionLuz:0.25,soles:160});
assert.equal(sinFallo.escalonada.perdidaKcal,0); assert.equal(sinFallo.sincronizada.perdidaKcal,0);
assert.notDeepEqual(x,comparar(datos,{inicio:40,duracion:7,fraccionLuz:0.75,soles:160}),'Duración y energía no afectan el resultado');
a.reiniciar(); assert.deepEqual(a.estado,crear().estado,'Reinicio incompleto');
console.log('P3: determinismo, conservación, cuatro fallos, bloqueo sin autorización, recuperación y comparación verificados.');
console.log(JSON.stringify(x,null,2));
