// node --experimental-websocket analysis/verificar_p3_navegador.mjs
// Chrome aislado, sin red; sólo stdlib y el cliente WebSocket nativo de Node 20.
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,writeFile,mkdir,readFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const raiz=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const perfil=await mkdtemp(path.join(os.tmpdir(),'milpa-chrome-'));
const chrome=spawn('google-chrome',['--headless=new','--no-sandbox','--disable-dev-shm-usage','--enable-unsafe-swiftshader','--use-angle=swiftshader','--remote-debugging-port=0','--no-first-run','--no-default-browser-check','--disable-background-networking','--user-data-dir='+perfil,'about:blank'],{stdio:['ignore','ignore','pipe']});
let socket;
try {
  console.log('Chrome: arranque aislado');
  const puerto=await new Promise((resolve,reject)=>{
    let salida='';chrome.stderr.on('data',d=>{salida+=d;const m=salida.match(/DevTools listening on ws:\/\/127.0.0.1:(\d+)/);if(m)resolve(Number(m[1]));});
    chrome.on('exit',c=>reject(new Error('Chrome terminó '+c)));setTimeout(()=>reject(new Error('Chrome no arrancó')),20000).unref();
  });
  const paginas=await(await fetch(`http://127.0.0.1:${puerto}/json/list`)).json();
  socket=new WebSocket(paginas.find(p=>p.type==='page').webSocketDebuggerUrl);
  await new Promise((r,j)=>{socket.onopen=r;socket.onerror=j;});
  let id=0;const pendientes=new Map(),errores=[],peticiones=[];
  socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pendientes.get(m.id);pendientes.delete(m.id);if(!p)return;m.error?p.reject(new Error(JSON.stringify(m.error))):p.resolve(m.result);}else if(m.method==='Runtime.consoleAPICalled'&&['error','assert'].includes(m.params.type))errores.push(m.params);else if(m.method==='Runtime.exceptionThrown')errores.push(m.params.exceptionDetails);else if(m.method==='Log.entryAdded'&&m.params.entry.level==='error')errores.push(m.params.entry);else if(m.method==='Network.requestWillBeSent')peticiones.push(m.params.request.url);};
  const cdp=(method,params={})=>new Promise((resolve,reject)=>{const numero=++id;const limite=setTimeout(()=>{pendientes.delete(numero);reject(new Error("Timeout CDP: "+method));},60000);pendientes.set(numero,{resolve:r=>{clearTimeout(limite);resolve(r)},reject:e=>{clearTimeout(limite);reject(e)}});socket.send(JSON.stringify({id:numero,method,params}));});
  const evaluar=async expression=>{const r=await cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
  const esperar=async expression=>{const limite=Date.now()+60000;while(Date.now()<limite){try{if(await evaluar(expression))return;}catch{}await new Promise(r=>setTimeout(r,250));}throw new Error('No se cumplió: '+expression+' errores '+JSON.stringify(errores));};
  await cdp('Runtime.enable');await cdp('Log.enable');await cdp('Network.enable');
  await cdp('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});
  await cdp('Network.setBlockedURLs',{urls:['http://*','https://*']});
  await cdp('Emulation.setDeviceMetricsOverride',{width:1920,height:1080,deviceScaleFactor:1,mobile:false});
  const html=path.join(process.env.MILPA_DEMO_DIR||path.join(raiz,'prototipo-3d'),'milpa360-simulador.html');
  const url=pathToFileURL(html).href;
  await cdp('Page.navigate',{url:url+'?vista=habitat&play=0&sol=62'});
  await esperar('typeof refsHab!=="undefined" && refsHab && !document.getElementById("carga")');
  assert.equal(await evaluar('modelo.estado.sol'),62);
  const cotas=await evaluar(`(()=>{gHabitat.updateMatrixWorld(true);const h=gHabitat.getObjectByName('referencia-humana'),b=new THREE.Box3().setFromObject(h);GEO.suelo.computeBoundingBox();GEO.marco.computeBoundingBox();return {piso:GEOM.casco.piso,pies:b.min.y,cabeza:b.max.y,techo:GEOM.casco.altura,figura:GEOM.casco.altura_figura,sueloMin:GEO.suelo.boundingBox.min.y,sueloMax:GEO.suelo.boundingBox.max.y,prof:GEOM.cartucho.profundidad_sustrato,marcoMax:GEO.marco.boundingBox.max.y,caja:GEOM.cartucho.altura_caja};})()`);
  assert.ok(cotas.cabeza<cotas.techo,'Figura no cabe bajo techo');
  assert.ok(Math.abs(cotas.sueloMin)<1e-6&&Math.abs(cotas.sueloMax-cotas.prof)<1e-6,'Sustrato sin profundidad nominal');
  assert.ok(Math.abs(cotas.marcoMax-cotas.caja)<1e-6,'Caja sin altura nominal');
  assert.ok(Math.abs(cotas.cabeza-cotas.piso-cotas.figura)<1e-6,'Escala humana inconsistente');
  const piso=await evaluar(`(()=>{const b=new THREE.Box3().setFromObject(gHabitat.getObjectByName('piso-modulo'));return {base:b.min.y,cara:b.max.y,terreno:gHabitat.getObjectByName('terreno').position.y};})()`);
  assert.ok(piso.terreno<=piso.base+1e-6&&Math.abs(piso.cara-cotas.piso)<1e-6,'Terreno invade piso transitable');
  console.log('Chrome: escena cargada sin red');
  const snap=await evaluar('JSON.stringify(modelo.estado)');
  await new Promise(r=>setTimeout(r,500));
  assert.equal(await evaluar('JSON.stringify(modelo.estado)'),snap,'Pausa muta el modelo');
  const alineacion=await evaluar(`(()=>{carrusel.grupo.updateMatrixWorld(true);return modelo.estado.lotes.map((l,i)=>{const p=new THREE.Vector3(R_MED,0,0);carrusel.bandejas[i].g.localToWorld(p);return Math.hypot(p.x-Math.cos(l.pos/N_POS*TAU)*R_MED,p.z-Math.sin(l.pos/N_POS*TAU)*R_MED);});})()`);
  assert.ok(alineacion.every(x=>x<1e-8),'Escena y posición del lote no coinciden');
  await evaluar('document.getElementById("b-tecnica").click()');
  await esperar('document.getElementById("datos-vivos")');
  await evaluar('document.getElementById("cam-planta").click()');
  assert.equal(await evaluar('camara.isOrthographicCamera'),true);
  await evaluar('document.getElementById("cam-lateral").click();document.getElementById("cam-orbita").click()');
  await evaluar('document.getElementById("aplicar-fallo").click();modelo.avanzar(1)');
  assert.equal(await evaluar('modelo.estado.aguaFraccion'),0);
  await evaluar('document.getElementById("reparar-fallo").click();modelo.avanzar(1)');
  assert.ok(await evaluar('modelo.estado.aguaFraccion>0'));
  await evaluar('document.getElementById("b-tormenta").click();modelo.avanzar(1)');
  assert.equal(await evaluar('modelo.estado.luz'),0.25);
  await evaluar('document.getElementById("b-tormenta").click();document.getElementById("b-reset").click()');
  assert.equal(await evaluar('modelo.estado.sol'),0);
  await evaluar('document.getElementById("tipo-fallo").value="lote";document.getElementById("aplicar-fallo").click();modelo.avanzar(9)');
  assert.equal(await evaluar('modelo.estado.pasos'),0);
  await evaluar('document.getElementById("aislar-lote").click();modelo.avanzar(1);modelo.verificar()');
  assert.equal(await evaluar('modelo.estado.cuarentena.length'),1);
  await evaluar('document.getElementById("comparar-siembras").click()');
  assert.ok((await evaluar('document.getElementById("cmp-resultado").textContent')).includes('escalonada'));
  await evaluar('document.getElementById("cmp-duracion").value=0;document.getElementById("cmp-calcular").click()');
  assert.ok((await evaluar('document.getElementById("cmp-resultado").textContent')).includes('0 kcal'));
  await evaluar('document.getElementById("cerrar").click();document.getElementById("b-reset").click();document.getElementById("b-play").click()');
  await esperar('modelo.estado.sol>0');await evaluar('document.getElementById("b-play").click()');
  await evaluar('document.getElementById("v-planeta").click()');await esperar('S.vista==="planeta"&&S.transicion===0');
  await evaluar('document.getElementById("v-habitat").click()');await esperar('S.vista==="habitat"&&S.transicion===0');
  const fichaErrores=await evaluar(`Object.keys(FICHAS).filter(k=>{abrirFicha(k);return !document.getElementById('f-viz').textContent;})`);assert.deepEqual(fichaErrores,[]);
  await evaluar('document.getElementById("cerrar").click()');
  await evaluar('document.getElementById("b-recorrido").click()');
  assert.ok((await evaluar('document.getElementById("f-tit").textContent')).includes('Módulo'));
  await evaluar('document.getElementById("cerrar").click()');
  console.log('Chrome: controles y geometría verificados');
  const hardware=await evaluar(`(()=>{const gl=renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info');return {three:THREE.REVISION,renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):'no disponible',pantalla:[innerWidth,innerHeight],dpr:devicePixelRatio};})()`);
  const fps=await evaluar('new Promise(resolve=>{let n=0;const inicio=performance.now();function contar(){if(++n===30)resolve(30000/(performance.now()-inicio));else requestAnimationFrame(contar);}requestAnimationFrame(contar);})');
  assert.equal(hardware.three,'160');
  const capturas=path.join(raiz,'docs/madrid/capturas');await mkdir(capturas,{recursive:true});
  const poses={hero:'vista=habitat&ui=0&sol=62&theta=-0.62&phi=1.08&dist=10.4&play=0',planta:'vista=habitat&ui=0&piso=0&casco=0&sol=62&theta=-1.5708&phi=0.12&dist=11.5&play=0',nucleo:'vista=habitat&ui=0&piso=0&sol=62&theta=-0.78&phi=1.16&dist=5.4&play=0',tormenta:'vista=habitat&ui=0&sol=62&storm=1&play=0&theta=-0.62&phi=1.04&dist=10',planeta:'ui=0&theta=-0.62&phi=1.30&dist=18.5&play=0',tecnica:'vista=habitat&play=0&sol=62'};
  for(const [nombre,q] of Object.entries(poses)){
    await cdp('Page.navigate',{url:url+'?'+q});await esperar('typeof refsHab!=="undefined"&&refsHab&&!document.getElementById("carga")');
    await evaluar('camara.position.copy(new THREE.Vector3(mira.x+orbe.dist*Math.sin(orbe.phi)*Math.cos(orbe.theta),mira.y+orbe.dist*Math.cos(orbe.phi),mira.z+orbe.dist*Math.sin(orbe.phi)*Math.sin(orbe.theta)))');
    if(nombre==='tecnica')await evaluar('abrirTecnica()');
    await evaluar('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
    console.log('Captura: '+nombre);
    const imagen=await cdp('Page.captureScreenshot',{format:'png'});
    await writeFile(path.join(capturas,nombre+'.png'),Buffer.from(imagen.data,'base64'));
  }
  assert.deepEqual(errores,[],'Errores de consola');
  assert.deepEqual(peticiones.filter(u=>/^https?:/.test(u)),[],'La demo solicita Internet');
  const informe={fecha:new Date().toISOString(),prueba:'Chrome headless, red deshabilitada, file://',browser:await cdp('Browser.getVersion'),cpu:os.cpus()[0].model,plataforma:os.platform(),...hardware,cotas,piso,fps30Frames:fps,limite:'SwiftShader por software; NO prueba del equipo del evento',controles:'pausa, avance, reset, fallos, cuarentena, vistas, fichas y comparación comprobados',errores,solicitudesHTTP:0};
  await writeFile(path.join(raiz,'docs/madrid/PRUEBA-P3-NAVEGADOR.json'),JSON.stringify(informe,null,2)+'\n');
  console.log(JSON.stringify(informe,null,2));
} finally {if(socket)socket.close();chrome.kill('SIGTERM');}
